### PR TITLE
Bump slurm from 17.11.5 to 19.05.1

### PR DESCRIPTION
**Pull request by crazyguitar**
Upgrade slurm to latest version 19.05.1

### CODE REVIEW

**Comment by mjstealey** [comment]
@crazyguitar - Looks good to me, I haven't tested it, but assume that you've run this in your environment successfully?

**Comment by crazyguitar** [comment]
Hi @mjstealey 

Yes! I run it successfully! I think write some unit tests will be better.

To prevent this project broken, I will write tests before merge. Thx

**Comment by mjstealey** [comment]
> Yes! I run it successfully! I think write some unit tests will be better.
> 
> To prevent this project broken, I will write tests before merge. Thx

@crazyguitar - This is fantastic!
Look forward to seeing your work 👍

**Comment by crazyguitar** [comment]
Hi @mjstealey 

I wrote some tests based on your REAEME.md and my design philosophy was using GNU make. Moreover, I used pure bash syntax instead of some other unit test frameworks such as [bats](https://github.com/bats-core/bats-core) because I didn't assume others that they had installed those frameworks. Please help me review the code and give me some suggestions. Thank you so much.

BTW, there are some targets in the Makefile: build, test, lint:

```bash
$ make build # or just make
$ make lint  # use shellcheck
$ make test  # run all tests in test/test.sh
``` 
Also, I created another branch, 19.05.1, on my fork project and used Travis CI to check whether all tests are pass or not. Please refer to the [test result](https://travis-ci.org/crazyguitar/slurm-in-docker) and my [.travisyml](https://github.com/crazyguitar/slurm-in-docker/blob/19.05.1/.travis.yml).

PS. .travis.yml doesn't include in this PR. 

thanks,
chang-ning

**Pull request merged**
